# Generated by Django 3.1.6 on 2021-02-03 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('eptype', models.CharField(choices=[('M', 'Main Story'), ('F', 'Filler')], default=('M', 'Main Story'), max_length=15)),
                ('description', models.TextField(max_length=250)),
                ('link', models.URLField(max_length=250)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.anime')),
            ],
        ),
    ]
