# Generated by Django 3.1.6 on 2021-02-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_profile_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='episode',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
